<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LeagueDataToolkit.Core\LeagueDataToolkit.Core.csproj" />
    <ProjectReference Include="..\LeagueDataToolkit.Configuration\LeagueDataToolkit.Configuration.csproj" />
    <ProjectReference Include="..\LeagueDataToolkit.FileFormats\LeagueDataToolkit.FileFormats.csproj" />
    <ProjectReference Include="..\LeagueDataToolkit.Transforms\LeagueDataToolkit.Transforms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
