<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LeagueDataToolkit.Core\LeagueDataToolkit.Core.csproj" />
    <ProjectReference Include="..\LeagueDataToolkit.Configuration\LeagueDataToolkit.Configuration.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
